#!/usr/bin/env python

Codes = {
    "body" : {
        "toroidal" : {
            "20": "Sdiff",
            "21": "S",
            "22": "SS",
            "23": "SSS",
            "24": "SSSS",
            "25": "ScS",
            "26": "ScSScS",
            "27": "ScSScSScS",
            "40": "sSdiff",
            "41": "s",
            "42": "sS",
            "43": "sSS",
            "44": "sSSS",
            "45": "sScS",
            "46": "sScSScS",
            "47": "sScSScSScS",
            "121": "S+ScS",
            "122": "SS+ScSScS",
            "123": "SSS+ScSScS",
            "124": "sS+sScS",
            "125": "SS+sS",
            "126": "SSS+sSS",
            "127": "SSSS+sSSS",
            "128": "SSS+sScSScS",
            "129": "SS+sScS",
            "140": "sSdiff+sScS",
            "141": "ScSScS+sSS",
            "142": "ScS+sS",
            "143": "SSSS+ScSScSScS",
            "144": "SS+ScS",
            "145": "sSSS+ScSScS",
            "146": "sScSScS+sSSS",
            "147": "sScSScS+sSS",
            "148": "SSSS+ScSScS",
            "149": "SSSS+sScSScS",
            "160": "Sdiff+sS",
            "1000": "unknown phase"
        },
        "spheroidal" : {
            "100": "Sdiff",
            "101": "S",
            "102": "SS",
            "103": "P",
            "104": "Pdiff",
            "105": "SSS",
            "106": "SSSS",
            "107": "PKPab",
            "108": "SKSac",
            "109": "PS",
            "110": "SP",
            "111": "R",
            "112": "ScSScSScS",
            "113": "not specified",
            "800": "unknown phase"
        }
    }
}
